# Generated by Django 2.2.5 on 2020-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title_ru', models.CharField(default='Неизвестное имя', max_length=200, verbose_name='Название покемона на русском')),
            ],
        ),
    ]
